### ISSUE TITLE
能否使用govcl制作呢

### ISSUE THREAD

**Issue by revolveyao** [user1121114685/115sha1#1]
有兴趣使用govcl制作吗？可以尝试下

**Comment by user1121114685** [comment]
> 有兴趣使用govcl制作吗？可以尝试下

你是对某些方面有需求吗？这也是我第一个gui程序。

**Comment by revolveyao** [comment]
> > 有兴趣使用govcl制作吗？可以尝试下
> 
> 你是对某些方面有需求吗？这也是我第一个gui程序。

只是感觉可以使用govcl做gui程序，可以尝试下，一起学习。

**Comment by user1121114685** [comment]
> > > 有兴趣使用govcl制作吗？可以尝试下
> > 
> > 
> > 你是对某些方面有需求吗？这也是我第一个gui程序。
> 
> 只是感觉可以使用govcl做gui程序，可以尝试下，一起学习。

大佬，fyne我学习了2天，才算会用。govcl是很好。有个大佬推荐过了，但更新频率没那么高。在没有需求之下的情况。我就不折腾了。如果大佬想通过govcl重写也十分欢迎。可以加我，也可以直接向项目提交pr，都十分欢迎。
