### ISSUE TITLE
软件是不是被官方屏蔽了，（21.8.5导入导出运行到20%左右就停止没有反应了）

### ISSUE THREAD

**Issue by tb0668** [user1121114685/115sha1#5]
软件是不是被官方屏蔽了，（21.8.5导入导出运行到20%左右就停止没有反应了）

**Comment by user1121114685** [comment]
你好，请不要再黑色控制台上乱点。如果不慎点击请再次点击黑色控制台，并按回车继续。

**Comment by user1121114685** [comment]
另外，安卓版/ios版即将完工。以后欢迎使用。

**Comment by tb0668** [comment]
大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？

**Comment by zi1shi** [comment]
> 软件是不是被官方屏蔽了，（21.8.5导入导出运行到20%左右就停止没有反应了）

我也遇到这种情况了    刚开没导入几个文件就卡住不动了

**Comment by user1121114685** [comment]
> > 软件是不是被官方屏蔽了，（21.8.5导入导出运行到20%左右就停止没有反应了）
> 
> 我也遇到这种情况了 刚开没导入几个文件就卡住不动了

看说明，不要点击黑色控制台。

**Comment by user1121114685** [comment]
> 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？

400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个

**Comment by zi1shi** [comment]
> > 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？
> 
> 400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个

2021/08/07 11:39:15 Fyne error:  Error getting file attributes
2021/08/07 11:39:15   Cause: The process cannot access the file because it is being used by another process.
2021/08/07 11:39:15   At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
2021/08/07 11:39:15 Fyne error:  Error getting file attributes
2021/08/07 11:39:15   Cause: The process cannot access the file because it is being used by another process.
2021/08/07 11:39:15   At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
这是我的报错提示

**Comment by user1121114685** [comment]
> > > 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？
> > 
> > 
> > 400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个
> 
> 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> 这是我的报错提示

基本无法复现。。。我只能建议你一个一个导入。

**Comment by user1121114685** [comment]
> > > 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？
> > 
> > 
> > 400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个
> 
> 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> 这是我的报错提示

基本无法复现。。。我只能建议你一个一个导入。

**Comment by zi1shi** [comment]
> > > > 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？
> > > 
> > > 
> > > 400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个
> > 
> > 
> > 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> > 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> > 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> > 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> > 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> > 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> > 这是我的报错提示
> 
> 基本无法复现。。。我只能建议你一个一个导入。
 关键这就是一个json文件


> > > > 大佬你好，软件点击扫码登录后经常显示：405，很抱歉。由于您访问的URL也可能对网站造成安全威胁，您的访问被阻断。你的请求ID是:784e2c9016282961565565723ad 。即是打不开盘里的内容，这是什么原因？
> > > 
> > > 
> > > 400系列一般是服务端设置的。具体原因只能等我复现才能解决。我想应该是使用过多导致的？好像现在每天上限是5万个
> > 
> > 
> > 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> > 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> > 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> > 2021/08/07 11:39:15 Fyne error: Error getting file attributes
> > 2021/08/07 11:39:15 Cause: The process cannot access the file because it is being used by another process.
> > 2021/08/07 11:39:15 At: c:/go/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/dialog/file_windows.go:76
> > 这是我的报错提示
> 
> 基本无法复现。。。我只能建议你一个一个导入。

这就是一个json文件，之前是可以正常导入的，今天发现不行了，换其他的json文件也不行，会在导入的过程中断

**Comment by zi1shi** [comment]
TG分享交流群也加不上。。找不到组织

**Comment by user1121114685** [comment]
https://github.com/gawwo/fake115-go/pull/16
我已向fake115-go 添加临时限速，等待大佬处理。从此以后高速导入可能是路人了！~

**Comment by user1121114685** [comment]
https://github.com/user1121114685/115sha1/commit/0bd6c9621dcd206a2d94430af8a12bf85d605e27
已经更新使用限速版本！

**Comment by zi1shi** [comment]
> [0bd6c96](https://github.com/user1121114685/115sha1/commit/0bd6c9621dcd206a2d94430af8a12bf85d605e27)
> 已经更新使用限速版本！

请问限速之后相对之前慢了多少呢

**Comment by tb0668** [comment]
不是工作台的原因，就是扫码登录会经常出现400问题，有时刷新出来内容了，但是一点导出文件，整个软件就会自动关闭退出，这可能是bug？专业的我也不懂，已经很感谢作者辛苦制作出来的软件了

**Comment by 1115sha1** [comment]
下载无法打开网页怎么办。。
