### ISSUE TITLE
大佬，软件还维护吗？好像不好用了，无法导入了，识别出来是0文件0目录

### ISSUE THREAD

**Issue by angussleeping** [user1121114685/115sha1#6]

**Comment by stanW98** [comment]
出现相同的问题了，问题描述为：ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value

**Comment by user1121114685** [comment]
> 出现相同的问题了，问题描述为：ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value

软件还在维护的，试试最新版本
